name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build ZMK
        uses: zmkfirmware/zmk-actions-unified@main
        with:
          args: --board seeeduino_xiao_ble --shield totem_left
